### ISSUE TITLE
PangAPI extension uses wrong link

### ISSUE THREAD

**Issue by AndrewScripter587** [PenguinMod/PenguinMod-ExtensionsGallery#113]
Updated issue:
the PangAPI extension is referenced using the incorrect URL in extensions.penguinmod.com.
it references
https://extensions.penguinmod.com/extensions/SammerLOL/extension.js
instead of
https://extensions.penguinmod.com/extensions/SammerLOL/pangapi.js
when clicking both copy url and view, resulting in a 404 being returned.
once, i clicked view on the PangAPI extension, and the editor actually crashed. attempted it again and the editor actually loaded, but without the extension.

Old issue:

the PangAPI extension in extensions.penguinmod.com will not load.

the reason why is the javascript file for the extension doesn't actually exist, going to the extension's js file by pasting the copied link results in a 404.

the js url that gets copied when i click Copy URL on the PangAPI extension in the gallery is:

https://extensions.penguinmod.com/extensions/SammerLOL/extension.js

which upon attempting to load, throws an error, and attempting to view the source in the browser by pasting the link above results in a 404 not found.

**Comment by wolfsyncc** [comment]
its because the link has extension.js even tho its named pangapi so use this link https://extensions.penguinmod.com/extensions/SammerLOL/pangapi.js

**Comment by AndrewScripter587** [comment]
ok, thanks. but that should really be fixed to use the correct link.

**Comment by JoshAtticus** [comment]
Fixed
