### ISSUE TITLE
Documentation UI Update 

### ISSUE THREAD

**Issue by Bashamega** [PenguinMod/PenguinMod-ExtensionsGallery#154]
Hello:)
I would like to update the design for the documentation, for UI.

I have created this documentation for April language and I was wondering if I can implement the same design or a similar design to PenguinMod, since the current documentation doesn't look nice.

This is a live preview of the documentation that I have created: https://merwin-asm.github.io/april/

If you accept please assign it to me

**Comment by JeremyGamer13** [comment]
- how would this look if the penguinmod design was applied (adding the top bar & how it would look when inside an extension's docs)
- theres a random switch in the top left of the docs that has no label or icon?
- doesnt seem to support both modes well
![image](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/69337718/4185c9f7-8edf-4a3d-8047-1204133cb99f)

**Comment by Bashamega** [comment]
> * how would this look if the penguinmod design was applied (adding the top bar & how it would look when inside an extension's docs)
> * theres a random switch in the top left of the docs that has no label or icon?
> * doesnt seem to support both modes well
>   ![image](https://private-user-images.githubusercontent.com/69337718/311491177-4185c9f7-8edf-4a3d-8047-1204133cb99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTUxMjAsIm5iZiI6MTcxMDA1NDgyMCwicGF0aCI6Ii82OTMzNzcxOC8zMTE0OTExNzctNDE4NWM5ZjctOGVkZi00YTNkLTgwNDctMTIwNDEzM2NiOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA3MTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmQ3N2I5ZTcwNTA2ZjYyYTEyZTdmN2ZhNmM2YmE0M2Y0MmFkNDVkMjBjODY1YTNkZWVhOWNjMWE5NDE3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ezmx_QExe9Lx2JEzFNVcZoAAdQ4ff_xki-aIem2ltqQ)

Correct, the owner wanted it to be simple, but i will modify so it can fit into the theme of the penguin Mod. Also, i will make it more advanced
