### ISSUE TITLE
Issue With Storage Extension

### ISSUE THREAD

**Issue by EricWilliamYT** [PenguinMod/PenguinMod-ExtensionsGallery#156]
I Don't Know Exactly Where To Post This But This Seemed Like The Most Appropriate Option.

I'm Using The PenguinMod Storage Extension, More Specifically The Server Storage Blocks.
I'm Trying To Make An Online Leaderboard For My Project And I Wanted To Put My Project On Neocities. Problem Is That When I Tried To Access The Leaderboard. It Wouldn't Let Me Connect. Apparently It Was Because Of A Content Security Policy Error. If You Can Help Me That Would Be Nice.

**Comment by RedMan13** [comment]
> if fucking cors caused this i’m gonna implode

tvat is ehat they said caused it

**Comment by RedMan13** [comment]
since this is a cors error and i dont know what the wrror is (or ecen if that would help) all i cab sa is we cant do anything since the requested was blocked by cors wither because the api endpoint dissaloud the wevsite url or because thebrequesting website dissaloud the url

**Comment by JeremyGamer13** [comment]
this issue doesnt seem to be talking about better storage

> oh wait i think gen1x turned the server off

**Comment by RedMan13** [comment]
indeed, also you xant cors error from a server response error so i dontbknow where you got that idea

**Comment by RedMan13** [comment]
> (i didn’t read too much of it, just kinda skimmed)
💀

**Comment by EricWilliamYT** [comment]
Ok, thanks for the input.

**Comment by RedMan13** [comment]
> indeed, also you can't get a cors error from a server error response so i dont know where you got that idea

on second thought, technically bot true
but its a massive technicality since the servers error handler must on its own volition send back to the requester a cors failure and also itself verify the incoming cors info, which for an error is unlikely, and this woild only happen if the server itself made the error and not he client saying the server request failed in place of the servers response
