### ISSUE TITLE
Where’s the Better Storage Extension?

### ISSUE THREAD

**Issue by wwtv127** [PenguinMod/PenguinMod-ExtensionsGallery#157]
So I Was Trying To Find The Better Storage Extension For Penguinmod On The PenguinMod Extra Extensions Page But For Some Reason, It Isn’t There Anymore. What Gives?

**Comment by JeremyGamer13** [comment]
yea based on previous messages it seems like gen1x isnt planning to bring back the servers so the extension is delisted unless they come back
