### ISSUE TITLE
permission to be included in Snail IDE's new gallery

### ISSUE THREAD

**Issue by dumorando** [PenguinMod/PenguinMod-ExtensionsGallery#185]
Snail ide has had some issues with "extension stealing" for a while so were revamping the extension system. The new extensions will be found at https://snail-ide.com/extensions and we need permission if we can fetch extensions from here.

**Comment by JeremyGamer13** [comment]
extensions are licensed MIT but the original creators will probably like it best if they are fetched from extensions.penguinmod.com & keep the proper crediting
so basically yes if you keep credits & fetch from extensions.penguinmod.com internally

**Comment by dumorando** [comment]
yeah thats what i was thinking thanks
