### ISSUE TITLE
`branchIconURI: null` doesn't work

### ISSUE THREAD

**Issue by PolyPenguinDev** [PenguinMod/PenguinMod-ExtensionsGallery#193]
My extension has many blocks that should look like conditions, but under the hood are loops. I need to remove the arrow, so to do this, i use `branchIconURI: null`, and it works on turbowarp, but not penguinmod

**TURBOWARP**
![image](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/56366826/0a15a977-47a4-40a8-9dcc-78a7de4238ab)

**PENGUINMOD**
![image](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/56366826/9dba7e1c-c995-4801-8ac2-e22fde2fb920)

**Comment by JeremyGamer13** [comment]
i believe a similar issue exists with long loop "chins" so will see if someone can make this match turbowarp

**Comment by SharkPool-SP** [comment]
> i believe a similar issue exists with long loop "chins" so will see if someone can make this match turbowarp

erm I did notice smt in the vm. but gsa said dont touch. Maybe you can look at it. DM me

**Comment by RedMan13** [comment]
yeaj i can go touch its balls real quick and see if it fixes this and doesnt expload everything

**Comment by RedMan13** [comment]
fizzed it
![image](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/74981904/8102f89f-5be2-4806-9d2a-592d12c9eb9d)
