### ISSUE TITLE
Box2D extension typo

### ISSUE THREAD

**Issue by immortalbean** [PenguinMod/PenguinMod-ExtensionsGallery#237]
In the file (static/extensions/pooiod/Box2D.js) the word "pollygon" is written on line 147 and 1016

**Comment by RedMan13** [comment]
is it in use of the pollygon menu piece.......

**Comment by RedMan13** [comment]
9k nvm, but whats wrong with pollygon
like even the google keyboard agrees its the correct spelling

**Comment by immortalbean** [comment]
I'm just saying that it was spelled, "polygon" everywhere else

**Comment by RedMan13** [comment]
no thats still valid spelling........

**Comment by immortalbean** [comment]
It's inconsistent

**Comment by RedMan13** [comment]
doooo{nt care about that 🥱

**Comment by JeremyGamer13** [comment]
skull

**Comment by CodeFoxy-Github** [comment]
TF

**Comment by Monochromasity** [comment]
you can just pull request a fix i guess?

**Comment by pooiod** [comment]
https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/pull/255
