### ISSUE TITLE
Issue with Sty-Lists when packaging to any

### ISSUE THREAD

**Issue by Monochromasity** [PenguinMod/PenguinMod-ExtensionsGallery#250]
I have a project that uses Sty-Lists to make a list's item size smaller (using a weird mechanic) but whenever I package it to any type, it breaks and I don't know why, as it works fine in the editor. I can't test embedding as I can't upload it to the server, so it doesn't have a valid link to embed it. What should I do?

The project as HTML is [here](https://livechatplus.vercel.app). Try it with a video/stream and you can see that the list breaks. However if you load up the project that you can download [here](https://livechatplus.vercel.app/livechatplus.pmp) it works fine in the editor.

**Comment by SharkPool-SP** [comment]
Can't view the file rn. But you should apply the changes once the list is visible.

**Comment by Monochromasity** [comment]
it is visible

**Comment by SharkPool-SP** [comment]
> it is visible

Can you show ur code

**Comment by Monochromasity** [comment]
> Can you show ur code with a image

The list is always visible, otherwise it wouldn't work in the editor. There's a lot of code so I don't know what specific snippet you want but this is where it gets formatted: 
![image](https://github.com/user-attachments/assets/c43f5b0e-6071-4db8-a33d-f3b82d885e2f)
(sorry if its a bit low quality, it was the biggest i could make it where everything was visible)

**Comment by SharkPool-SP** [comment]
> > Can you show ur code with a image
> 
> 
> 
> The list is always visible, otherwise it wouldn't work in the editor. There's a lot of code so I don't know what specific snippet you want but this is where it gets formatted: 
> 
> ![image](https://github.com/user-attachments/assets/c43f5b0e-6071-4db8-a33d-f3b82d885e2f)
> 
> (sorry if its a bit low quality, it was the biggest i could make it where everything was visible)

When is the chat message called.

**Comment by Monochromasity** [comment]
I can't get a picture right now but it is called whenever you load a video. When you said "you should apply the changes once the list is visible", I ran into this issue when I was making it, but fixed it by keeping the list visible at all times. I don't know why it is working in the editor but not when packaged and I think it might be to do with the extension but I could be wrong. I'm also wondering if that now the servers are (sort of) (not really) back up now, would embedding it work? (The reason I couldn't before is because it needed a link to embed)

**Comment by SharkPool-SP** [comment]
Figured it out. The issue is simply the weird mechanic you are using. It is not intentional.

Fun Fact: Monitors are built different in the Editor and Packager

Either way, this is not my problem, you need to find a workaround. Potentially use my DOM Selector extension to mess with the monitor directly without using weird mechanics
