### ISSUE TITLE
Can't upload .pmp files to PenguinMod on iPad

### ISSUE THREAD

**Issue by Monochromasity** [PenguinMod/PenguinMod-ExtensionsGallery#252]
Hi,

For some reason when I try to load a project to PenguinMod on an iPad it just doesn't let me upload .pmp files, it just shows it as greyed out, as if the file extension was incorrect. Does anyone know how to fix it or is it an issue with iOS/PenguinMod? I can attach pictures if needed but it might take a while for me to get them sorry :(

**Comment by SharkPool-SP** [comment]
its a issue with iOS

**Comment by SharkPool-SP** [comment]
you could use the load project from data.uri block in runtime as a alternative

**Comment by Monochromasity** [comment]
wait thats a block? what extension

**Comment by JeremyGamer13** [comment]
you can just rename it to .pm
for some reason safari doesnt support a 9 year old feature so it only lets you choose .pm files, not .pmp

**Comment by Monochromasity** [comment]
oh ok thanks

**Comment by Monochromasity** [comment]
> you can just rename it to .pm for some reason safari doesnt support a 9+ year old feature so it only lets you choose .pm files, not .pmp

it works, thanks for the info
