### ISSUE TITLE
 extension in_app_shopping

### ISSUE THREAD

**Issue by Moncef101613** [PenguinMod/PenguinMod-ExtensionsGallery#55]
It would be great if I could add items for purchase within my game, such as monthly subscriptions, charging jewelry, money, or characters within my game.

**Comment by Moncef101613** [comment]
**This may help**
https://github.com/GDevelopApp/GDevelop-extensions/blob/main/extensions/reviewed/InAppPurchase.json

**Comment by RedMan13** [comment]
nuh uh

**Comment by wolfieboy09** [comment]
No microtransactions

**Comment by JoshAtticus** [comment]
Stale

**Comment by RedMan13** [comment]
> Stale

troled
