### ISSUE TITLE
The design of the Penguin Mod is the same as that of TurboWarp. Why?

### ISSUE THREAD

**Issue by WAYLIVES** [PenguinMod/PenguinMod-ExtensionsGallery#67]
Why do you have the design of the Penguin Mod program coincides with the design of TurboWarp? Are you doing this on purpose or would you be happy if there was an opportunity to change the design?

**Comment by Monochromasity** [comment]
I think it's because A) Because it's based on TurboWarp, and B) Because it makes it easier for people used to TurboWarp to use PenguinMod as the layout is the same.

**Comment by WAYLIVES** [comment]
> I think it's because A) Because it's based on TurboWarp, and B) Because it makes it easier for people used to TurboWarp to use PenguinMod as the layout is the same.

In principle I agree with you ;)

**Comment by JeremyGamer13** [comment]
this is just mainly because we are completely based on turbowarp, we have changed some parts like the extension library for example but making huge changes might confuse people & we mostly just agree that the UI looks fine already
