### ISSUE TITLE
Add scrandled to Extensions Menu in PM Editor

### ISSUE THREAD

**Issue by Monochromasity** [PenguinMod/PenguinMod-ExtensionsGallery#91]
Hi, so this was originally a pull request and is now redirected to an issue, but could someone add my extension list ("scrandled", https://scrandled.vercel.app) to the Extensions menu in the PenguinMod editor? My first extension that got accepted took a very long time to get accepted, so I think it would be easier just to add it to my own website instead. Is that fine with you?

**Comment by nmsderp** [comment]
this issue would be better to be placed on the penguinmod.github.io repo

**Comment by RedMan13** [comment]
> this issue would be better to be placed on the penguinmod.github.io repo

false

**Comment by SharkPool-SP** [comment]
no

**Comment by nmsderp** [comment]
ok, i was just thinking that since if it were to be there it would be in the ext gallery or something

**Comment by nmsderp** [comment]
so i guess it can stay here for now

**Comment by JoshAtticus** [comment]
> Hi, so this was originally a pull request and is now redirected to an issue, but could someone add my extension list ("scrandled", https://scrandled.vercel.app) to the Extensions menu in the PenguinMod editor? My first extension that got accepted took a very long time to get accepted, so I think it would be easier just to add it to my own website instead. Is that fine with you?

No, please make a pull request to add your extension to the PenguinMod Extension Gallery.

**Comment by Monochromasity** [comment]
> > Hi, so this was originally a pull request and is now redirected to an issue, but could someone add my extension list ("scrandled", https://scrandled.vercel.app) to the Extensions menu in the PenguinMod editor? My first extension that got accepted took a very long time to get accepted, so I think it would be easier just to add it to my own website instead. Is that fine with you?
> 
> No, please make a pull request to add your extension to the PenguinMod Extension Gallery.

You don't get it, it takes a long time for extensions to get accepted so I wanted to make my own extension collection like SharkPool's one and I wanted someone to add it to the extensions menu in the EDITOR, not the extension gallery. It isn't an extension so I can't make a pull request for it and I can't add it to the extension gallery because I don't think any extension collections are allowed there.

The only reason I made scrandled is because you guys take so long to add an extension, I thought it would be easier if I added people's extensions to a list too (if they wanted) and they could access it from the Extensions Menu in the editor.

**Comment by JoshAtticus** [comment]
> > > Hi, so this was originally a pull request and is now redirected to an issue, but could someone add my extension list ("scrandled", https://scrandled.vercel.app) to the Extensions menu in the PenguinMod editor? My first extension that got accepted took a very long time to get accepted, so I think it would be easier just to add it to my own website instead. Is that fine with you?
> > 
> > 
> > No, please make a pull request to add your extension to the PenguinMod Extension Gallery.
> 
> You don't get it, it takes a long time for extensions to get accepted so I wanted to make my own extension collection like SharkPool's one and I wanted someone to add it to the extensions menu in the EDITOR, not the extension gallery. It isn't an extension so I can't make a pull request for it and I can't add it to the extension gallery because I don't think any extension collections are allowed there.
> 
> The only reason I made scrandled is because you guys take so long to add an extension, I thought it would be easier if I added people's extensions to a list too (if they wanted) and they could access it from the Extensions Menu in the editor.

The reason we take so long is because we're busy updating not only the frontend but our server too. **You** don't get it, we have 4 developers doing everything and we're in the process of merging 1000+ Turbowarp commits, rewriting server and replying to issues and pull requests.

**Comment by RedMan13** [comment]
> > > > Hi, so this was originally a pull request and is now redirected to an issue, but could someone add my extension list ("scrandled", https://scrandled.vercel.app) to the Extensions menu in the PenguinMod editor? My first extension that got accepted took a very long time to get accepted, so I think it would be easier just to add it to my own website instead. Is that fine with you?
> > > 
> > > 
> > > No, please make a pull request to add your extension to the PenguinMod Extension Gallery.
> > 
> > 
> > You don't get it, it takes a long time for extensions to get accepted so I wanted to make my own extension collection like SharkPool's one and I wanted someone to add it to the extensions menu in the EDITOR, not the extension gallery. It isn't an extension so I can't make a pull request for it and I can't add it to the extension gallery because I don't think any extension collections are allowed there.
> > The only reason I made scrandled is because you guys take so long to add an extension, I thought it would be easier if I added people's extensions to a list too (if they wanted) and they could access it from the Extensions Menu in the editor.
> 
> The reason we take so long is because we're busy updating not only the frontend but our server too. **You** don't get it, we have 4 developers doing everything and we're in the process of merging 1000+ Turbowarp commits, rewriting server and replying to issues and pull requests.

not to mention that out of all four devs only one is performing the verification of extension pr's rn
